# Generated by Django 4.0.6 on 2022-07-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
