# Generated by Django 4.0.6 on 2022-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=30)),
                ('book_year', models.CharField(max_length=4)),
                ('book_type', models.CharField(max_length=30)),
                ('book_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('book_availabel', models.BooleanField(default=True)),
                ('book_quantity', models.IntegerField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
