# Generated by Django 4.0.6 on 2022-07-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_availabel',
            new_name='book_available',
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(default=False, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_quantity',
            field=models.IntegerField(),
        ),
    ]
