# Generated by Django 4.0.6 on 2022-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_book_availabel_book_book_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=45),
        ),
    ]
